# Generated by Django 5.0 on 2023-12-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Товары',
            fields=[
                ('номер_товара', models.AutoField(primary_key=True, serialize=False)),
                ('наименование', models.CharField(max_length=255)),
                ('единица_измерения', models.CharField(max_length=255)),
                ('цена', models.FloatField()),
            ],
        ),
    ]
