# Generated by Django 5.0 on 2023-12-06 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customer_worker_raw_delete_товары_products_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products_list',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='raw',
            name='products_list',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.DeleteModel(
            name='Products_list',
        ),
        migrations.DeleteModel(
            name='Raw',
        ),
    ]
